/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Add them to your .env file (see docs/PROJECT_SPEC.md).`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

const isClient = typeof window !== "undefined";

function getDemoRole() {
  if (!isClient) return null;
  return localStorage.getItem("nexus_demo_role");
}

function createMockQueryBuilder(data: any) {
  const builder = {
    select: () => builder,
    eq: () => builder,
    neq: () => builder,
    in: () => builder,
    order: () => builder,
    limit: () => builder,
    maybeSingle: async () => ({ data: Array.isArray(data) ? data[0] : data, error: null }),
    single: async () => ({ data: Array.isArray(data) ? data[0] : data, error: null }),
    then: (resolve: any) => resolve({ data, error: null }),
  };
  return builder as any;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();

    const role = getDemoRole();
    if (role) {
      if (prop === "auth") {
        const originalAuth = _supabase.auth;
        const mockUser = {
          id: "demo-user-id-1234-5678",
          aud: "authenticated",
          role: "authenticated",
          email: `${role}@nexusiot.pk`,
          email_confirmed_at: new Date().toISOString(),
          phone: "+92 332 3059259",
          confirmed_at: new Date().toISOString(),
          last_sign_in_at: new Date().toISOString(),
          app_metadata: {},
          user_metadata: {
            full_name:
              role === "super_admin"
                ? "Muhammad Huzaifa (Super Admin)"
                : role === "admin"
                  ? "Sarah Khan (Platform Admin)"
                  : role === "vendor"
                    ? "Ali Raza (IoT Vendor)"
                    : "Zainab Fatima (Customer)",
          },
          identities: [],
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        };

        const mockSession = {
          access_token: "demo-token",
          token_type: "bearer",
          expires_in: 3600,
          refresh_token: "demo-refresh-token",
          user: mockUser,
          expires_at: Math.floor(Date.now() / 1000) + 3600,
        };

        return new Proxy(originalAuth, {
          get(authTarget, authProp) {
            if (authProp === "getSession") {
              return async () => ({ data: { session: mockSession }, error: null });
            }
            if (authProp === "getUser") {
              return async () => ({ data: { user: mockUser }, error: null });
            }
            if (authProp === "onAuthStateChange") {
              return (callback: any) => {
                // Initial callback invocation
                callback("SIGNED_IN", mockSession);

                const handler = () => {
                  const updatedRole = getDemoRole();
                  if (updatedRole) {
                    callback("SIGNED_IN", {
                      ...mockSession,
                      user: {
                        ...mockUser,
                        email: `${updatedRole}@nexusiot.pk`,
                        user_metadata: {
                          full_name:
                            updatedRole === "super_admin"
                              ? "Muhammad Huzaifa (Super Admin)"
                              : updatedRole === "admin"
                                ? "Sarah Khan (Platform Admin)"
                                : updatedRole === "vendor"
                                  ? "Ali Raza (IoT Vendor)"
                                  : "Zainab Fatima (Customer)",
                        },
                      },
                    });
                  } else {
                    callback("SIGNED_OUT", null);
                  }
                };

                window.addEventListener("nexus-auth-update", handler);
                return {
                  data: {
                    subscription: {
                      unsubscribe() {
                        window.removeEventListener("nexus-auth-update", handler);
                      },
                    },
                  },
                };
              };
            }
            if (authProp === "signOut") {
              return async () => {
                localStorage.removeItem("nexus_demo_role");
                window.dispatchEvent(new Event("nexus-auth-update"));
                return originalAuth.signOut();
              };
            }
            return Reflect.get(authTarget, authProp);
          },
        });
      }

      if (prop === "from") {
        return (table: string) => {
          if (table === "user_roles") {
            const list = [role];
            if (role === "super_admin") {
              list.push("admin", "vendor", "user");
            } else if (role === "admin") {
              list.push("vendor", "user");
            } else if (role === "vendor") {
              list.push("user");
            }
            return createMockQueryBuilder(
              list.map((r) => ({ role: r, user_id: "demo-user-id-1234-5678" })),
            );
          }
          if (table === "vendors") {
            return createMockQueryBuilder([
              {
                id: "demo-vendor-id-1234",
                user_id: "demo-user-id-1234-5678",
                shop_name: "Demo IoT Store",
                slug: "demo-iot-store",
                commission_pct: 10,
                is_active: true,
                created_at: new Date().toISOString(),
              },
            ]);
          }
          if (table === "profiles") {
            return createMockQueryBuilder([
              {
                id: "demo-user-id-1234-5678",
                full_name:
                  role === "super_admin"
                    ? "Muhammad Huzaifa (Super Admin)"
                    : role === "admin"
                      ? "Sarah Khan (Platform Admin)"
                      : role === "vendor"
                        ? "Ali Raza (IoT Vendor)"
                        : "Zainab Fatima (Customer)",
                phone: "+92 332 3059259",
                created_at: new Date().toISOString(),
                updated_at: new Date().toISOString(),
              },
            ]);
          }
          return Reflect.get(_supabase!, "from").call(_supabase, table);
        };
      }
    }

    return Reflect.get(_supabase || {}, prop, receiver);
  },
});
